export { default as Actors } from "./Actors/Actors";
export { default as Moviess } from "./Moviess/Movies";
export { default as MoviesInformation } from "./MovieInformation/MovieInformation";
export { default as Profile } from "./Profile/Profile";
export { default as NavBar } from "./NavBar/NavBar";
export { default as Sidebar } from "./Sidebar/Sidebar";
export { default as MovieList } from "./MovieList/MoviesList";
export { default as Movie } from "./Moviee/Movie";
export { default as Search } from "./Search/Search";
